language: ruby
rvm:
  - "2.0.0"
  - "2.1.10"
  - "2.2.7"
  - "2.3.4"
  - "2.4.1"
install: bundle install && ./autogen.sh && git config --global user.name 'Travis' && git config --global user.email 'travis@example.com'
script: RUBY=$(which ruby) ./configure && make && bundle exec rspec
