language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.5"
  - "2.2.3"
  - "2.3.1"
install: bundle install && ./autogen.sh && git config --global user.name 'Travis' && git config --global user.email 'travis@example.com'
script: RUBY=$(which ruby) ./configure && make && bundle exec rspec
